go_binary(
    name = "puku",
    srcs = ["puku.go"],
    visibility = ["PUBLIC"],
    deps = [
        "///third_party/go/github.com_peterebden_go-cli-init_v5//flags",
        "///third_party/go/github.com_peterebden_go-cli-init_v5//logging",
        "//config",
        "//generate",
        "//licences",
        "//logging",
        "//migrate",
        "//please",
        "//proxy",
        "//watch",
        "//work",
    ],
)
