version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - misspell
    - nilerr
    - prealloc
    - revive
    - thelper
    - unconvert
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/please-build/puku)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
