go_library(
    name = "options",
    srcs = ["options.go"],
    visibility = [
        "//cmd/puku:all",
        "//generate:all",
        "//graph:all",
        "//licences:all",
        "//migrate:all",
        "//sync/integration/syncmod:all",
        "//watch:all",
    ],
)
