// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: generate/test_data/foo/foo.go

package foo

import _ "github.com/example/gen_module"
