package knownimports

import (
	"go/build"
	"os"
	"path/filepath"
	"strings"
)

// Optimisation to avoid going to disk. We still check incase a new Go version includes a new package.
var goRootImports = map[string]struct{}{
	"archive/tar":                       {},
	"archive/zip":                       {},
	"bufio":                             {},
	"bytes":                             {},
	"compress/bzip2":                    {},
	"compress/flate":                    {},
	"compress/gzip":                     {},
	"compress/lzw":                      {},
	"compress/zlib":                     {},
	"container/heap":                    {},
	"container/list":                    {},
	"container/ring":                    {},
	"context":                           {},
	"crypto":                            {},
	"database/sql/driver":               {},
	"database/sql":                      {},
	"debug/dwarf":                       {},
	"debug/elf":                         {},
	"debug/gosym":                       {},
	"debug/macho":                       {},
	"debug/pe":                          {},
	"debug/plan9obj":                    {},
	"embed":                             {},
	"encoding/ascii85":                  {},
	"encoding/asn1":                     {},
	"encoding/base32":                   {},
	"encoding/base64":                   {},
	"encoding/binary":                   {},
	"encoding/csv":                      {},
	"encoding/gob":                      {},
	"encoding/hex":                      {},
	"encoding":                          {},
	"encoding/json":                     {},
	"encoding/pem":                      {},
	"encoding/xml":                      {},
	"errors":                            {},
	"expvar":                            {},
	"flag":                              {},
	"fmt":                               {},
	"go/ast":                            {},
	"go/build/constraint":               {},
	"go/build":                          {},
	"go/constant":                       {},
	"go/doc":                            {},
	"go/format":                         {},
	"go/importer":                       {},
	"go/internal/gccgoimporter":         {},
	"go/internal/gcimporter":            {},
	"go/internal/srcimporter":           {},
	"go/internal/typeparams":            {},
	"go/parser":                         {},
	"go/printer":                        {},
	"go/scanner":                        {},
	"go/token":                          {},
	"go/types":                          {},
	"hash/adler32":                      {},
	"hash/crc32":                        {},
	"hash/crc64":                        {},
	"hash/fnv":                          {},
	"hash":                              {},
	"hash/maphash":                      {},
	"html":                              {},
	"html/template":                     {},
	"image/color":                       {},
	"image/color/palette":               {},
	"image/draw":                        {},
	"image/gif":                         {},
	"image":                             {},
	"image/internal/imageutil":          {},
	"image/jpeg":                        {},
	"image/png":                         {},
	"index/suffixarray":                 {},
	"internal/abi":                      {},
	"internal/buildcfg":                 {},
	"internal/bytealg":                  {},
	"internal/cfg":                      {},
	"internal/cpu":                      {},
	"internal/execabs":                  {},
	"internal/fmtsort":                  {},
	"internal/goexperiment":             {},
	"internal/goroot":                   {},
	"internal/goversion":                {},
	"internal/itoa":                     {},
	"internal/lazyregexp":               {},
	"internal/lazytemplate":             {},
	"internal/nettrace":                 {},
	"internal/obscuretestdata":          {},
	"internal/oserror":                  {},
	"internal/poll":                     {},
	"internal/profile":                  {},
	"internal/race":                     {},
	"internal/reflectlite":              {},
	"internal/singleflight":             {},
	"internal/syscall/execenv":          {},
	"internal/syscall/unix":             {},
	"internal/sysinfo":                  {},
	"internal/testenv":                  {},
	"internal/testlog":                  {},
	"internal/trace":                    {},
	"internal/unsafeheader":             {},
	"internal/xcoff":                    {},
	"io/fs":                             {},
	"io":                                {},
	"io/ioutil":                         {},
	"log":                               {},
	"log/syslog":                        {},
	"math/big":                          {},
	"math/bits":                         {},
	"math/cmplx":                        {},
	"math":                              {},
	"math/rand":                         {},
	"mime":                              {},
	"mime/multipart":                    {},
	"mime/quotedprintable":              {},
	"net":                               {},
	"net/http/cgi":                      {},
	"net/http/cookiejar":                {},
	"net/http/fcgi":                     {},
	"net/http":                          {},
	"net/http/httptest":                 {},
	"net/http/httptrace":                {},
	"net/http/httputil":                 {},
	"net/http/internal/ascii/please":    {},
	"net/http/internal":                 {},
	"net/http/internal/testcert/please": {},
	"net/http/pprof":                    {},
	"net/internal/socktest":             {},
	"net/mail":                          {},
	"net/rpc":                           {},
	"net/rpc/jsonrpc":                   {},
	"net/smtp":                          {},
	"net/textproto":                     {},
	"net/url":                           {},
	"os/exec":                           {},
	"os":                                {},
	"os/signal":                         {},
	"os/signal/internal/pty/please":     {},
	"os/user":                           {},
	"path/filepath":                     {},
	"path":                              {},
	"plugin":                            {},
	"reflect":                           {},
	"reflect/internal/example1":         {},
	"reflect/internal/example2":         {},
	"regexp":                            {},
	"regexp/syntax":                     {},
	"runtime/cgo":                       {},
	"runtime/debug":                     {},
	"runtime":                           {},
	"runtime/internal/atomic":           {},
	"runtime/internal/math":             {},
	"runtime/internal/sys":              {},
	"runtime/metrics":                   {},
	"runtime/pprof":                     {},
	"runtime/race":                      {},
	"runtime/trace":                     {},
	"sort":                              {},
	"strconv":                           {},
	"strings":                           {},
	"sync/atomic":                       {},
	"sync":                              {},
	"syscall":                           {},
	"testing/fstest":                    {},
	"testing":                           {},
	"testing/internal/testdeps":         {},
	"testing/iotest":                    {},
	"testing/quick":                     {},
	"text/scanner":                      {},
	"text/tabwriter":                    {},
	"text/template":                     {},
	"text/template/parse":               {},
	"time":                              {},
	"time/tzdata":                       {},
	"unicode":                           {},
	"unicode/utf16":                     {},
	"unicode/utf8":                      {},
	"unsafe":                            {},
}

func IsInGoRoot(i string) bool {
	if strings.HasPrefix(i, "crypto/") {
		return true
	}
	_, ok := goRootImports[i]
	if ok {
		return true
	}

	b := build.Default
	path := filepath.Join(b.GOROOT, "pkg", b.GOOS+"_"+b.GOARCH, i+".a")
	if _, err := os.Lstat(path); err == nil {
		goRootImports[i] = struct{}{}
		return true
	}
	return false
}
