go_library(
    name = "config",
    srcs = ["config.go"],
    visibility = [
        "//:all",
        "//generate:all",
        "//graph:all",
        "//migrate:all",
        "//work:all",
    ],
    deps = ["//kinds"],
)
