go_library(
    name = "proxy",
    srcs = ["proxy.go"],
    visibility = ["//generate:all"],
    deps = [
        "///third_party/go/golang.org_x_mod//modfile",
        "///third_party/go/golang.org_x_mod//semver",
    ],
)
