go_library(
    name = "kinds",
    srcs = ["kinds.go"],
    visibility = [
        "//config",
        "//generate:all",
        "//plz-out/tmp/generate/_generate#pkg_info._build/generate:all",
    ],
)
