go_library(
    name = "work",
    srcs = ["work.go"],
    visibility = [
        "//:all",
        "//cmd/puku:all",
        "//generate",
        "//watch",
    ],
    deps = [
        "///third_party/go/github.com_bazelbuild_buildtools//labels",
        "//config",
    ],
)
