go_library(
    name = "please",
    srcs = [
        "build.go",
        "please.go",
        "query_config.go",
    ],
    visibility = [
        "//:all",
        "//generate:all",
        "//migrate:all",
        "//watch:all",
    ],
)
