go_library(
    name = "please",
    srcs = [
        "build.go",
        "please.go",
        "query_config.go",
    ],
    visibility = [
        "//:all",
        "//cmd/puku:all",
        "//generate:all",
        "//generate/integration/syncmod:all",
        "//licences:all",
        "//migrate:all",
        "//plz-out/tmp/generate/_generate#pkg_info._build/generate:all",
        "//watch:all",
    ],
)
