go_library(
    name = "please",
    srcs = [
        "build.go",
        "please.go",
        "query_config.go",
    ],
    visibility = [
        "//:all",
        "//cmd/puku:all",
        "//eval:all",
        "//generate:all",
        "//generate/integration/syncmod:all",
        "//licences:all",
        "//migrate:all",
        "//sync:all",
        "//sync/integration/syncmod:all",
        "//watch:all",
    ],
)
