go_library(
    name = "harness",
    srcs = ["harness.go"],
    visibility = ["//e2e/tests/codegen:all"],
    deps = [
        "///third_party/go/github.com_please-build_buildtools//build",
        "///third_party/go/golang.org_x_sys//execabs",
        "//config",
    ],
)
