name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.23"
      - name: Build go_root_packages
        # This makes sure the knownimports/go_root_packages file exists as a real file for golangci-lint
        run: ./pleasew build //knownimports:go_root_packages && mv $(readlink knownimports/go_root_packages) knownimports/go_root_packages
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.61.0
